title: Veronica Upadhyay
logo: IMG_4155.PNG
linkedin: veronicaupadhyay-70a718234
description: Veronica Upadhyay is a Statistics B.S student with a passion for biostatistics. 
In 2024, Veronica was awarded the UNC Summer Undergraduate Research Fellowship to independently 
analyze the probabilistic the risks of enteric illnesses for MAPSAN using Quantitative Microbial 
Risk Assessment (QMRA). She has been designing R programs for MAPSAN to expedite data cleaning 
and provide insightful summary statistics since Fall 2022. Veronica is interested in research exploring 
connections between existing structures and health disparities.
# show_downloads: true
theme: jekyll-theme-minimal

