title: Veronica Upadhyay
logo: IMG_4155.PNG
description: Veronica Upadhyay is a Stats major at UNC Chapel Hill. In 2024, Veronica was awarded UNC SURF— a grant to compute the probabilistic the risks of enteric illnesses among a community in Maputo Mozambique by building mathematical prediction models. Veronica research interests are to explore connections between existing structures and health disparities.
linkedin_username: veronicaupadhyay-70a718234
# show_downloads: true
theme: jekyll-theme-minimal

