title: Veronica Upadhyay
logo: IMG_4155.PNG
description: Veronica Upadhyay is a Statistics B.S student with a passion for biostatistics. In 2024, Veronica was awarded the UNC Summer Undergraduate Research Fellowship grant to independently analyze the probabilistic the risks of enteric illnesses by building mathematical models with Quantitative Microbial Risk Assessment (QMRA) methods. Veronica research interests are to explore connections between existing structures and health disparities.
linkedin: veronicaupadhyay-70a718234
# show_downloads: true
theme: jekyll-theme-minimal

