title: Veronica Upadhyay
logo: <p align="left">
  <img src="upadhyay_veronica_jan_2025_2.JPG" alt="Veronica Upadhyay" width="150" style="border-radius: 50%; object-fit: cover;">
</p>

# description: text below image
# show_downloads: true
theme: jekyll-theme-minimal
